import React, { useState } from 'react';
import { FileBarChart2, Download, FileText, Shield, Flame, ClipboardCheck, AlertTriangle, ChevronRight, CheckCircle } from 'lucide-react';
import PageHeader from '../components/ui/PageHeader';
import { buildings } from '../data/mockData';

const reports = [
  {
    id: 'RPT-001',
    title: 'Compliance Summary Report',
    description: 'Full portfolio compliance overview with building scores, audit status, and regulatory gap analysis.',
    icon: Shield,
    color: '#22C55E',
    bg: '#F0FDF4',
    formats: ['PDF', 'Excel'],
    lastGenerated: '2026-06-01',
    pages: '12-18 pages'
  },
  {
    id: 'RPT-002',
    title: 'Audit History Report',
    description: 'Comprehensive audit trail with findings, auditor notes, compliance scores, and remediation status.',
    icon: ClipboardCheck,
    color: '#3B82F6',
    bg: '#EFF6FF',
    formats: ['PDF', 'Excel'],
    lastGenerated: '2026-05-28',
    pages: '8-14 pages'
  },
  {
    id: 'RPT-003',
    title: 'Extinguisher Status Report',
    description: 'Complete inventory status, expiry tracking, replacement schedule, and maintenance log.',
    icon: Flame,
    color: '#F59E0B',
    bg: '#FFFBEB',
    formats: ['PDF', 'Excel'],
    lastGenerated: '2026-06-03',
    pages: '6-10 pages'
  },
  {
    id: 'RPT-004',
    title: 'Risk Assessment Report',
    description: 'AI-generated risk analysis with building risk scores, factor breakdown, and prioritized recommendations.',
    icon: AlertTriangle,
    color: '#EF4444',
    bg: '#FEF2F2',
    formats: ['PDF', 'Excel'],
    lastGenerated: '2026-06-05',
    pages: '15-22 pages'
  },
];

const recentReports = [
  { name: 'Q2-2026 Compliance Summary.pdf', date: '2026-06-05', size: '2.4 MB', type: 'PDF' },
  { name: 'Prism Corporate Center Risk Assessment.pdf', date: '2026-06-03', size: '1.8 MB', type: 'PDF' },
  { name: 'May-2026 Extinguisher Report.xlsx', date: '2026-06-01', size: '0.9 MB', type: 'Excel' },
  { name: 'Portfolio Audit History Q2.pdf', date: '2026-05-28', size: '3.1 MB', type: 'PDF' },
];

export default function Reports() {
  const [generating, setGenerating] = useState(null);
  const [generated, setGenerated] = useState(null);
  const [selectedBuilding, setSelectedBuilding] = useState('All Buildings');
  const [selectedPeriod, setSelectedPeriod] = useState('Q2 2026 (Apr-Jun)');

  const filteredRecentReports = React.useMemo(() => {
    let filtered = [...recentReports];
    if (selectedBuilding !== 'All Buildings') {
      filtered = filtered.filter(r => r.name.toLowerCase().includes(selectedBuilding.toLowerCase().split(' ')[0]));
    }
    if (selectedPeriod !== 'Q2 2026 (Apr-Jun)') {
      // Filter by period keyword match in report names
      filtered = filtered.filter(r => r.name.toLowerCase().includes(selectedPeriod.slice(0, 4).toLowerCase()));
    }
    return filtered;
  }, [selectedBuilding, selectedPeriod]);

  const handleGenerate = (report, format) => {
    setGenerating(report.id);
    setGenerated(null);
    setTimeout(() => {
      const ext = format === 'PDF' ? 'pdf' : format === 'Excel' ? 'xlsx' : 'csv';
      // Build realistic report content
      const content = `Report: ${report.title || report.name}\nScope: ${selectedBuilding}\nPeriod: ${selectedPeriod}\nGenerated: ${new Date().toISOString()}\n\nThis report was generated by FireGuard AI.`;
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${report.id || 'report'}-${selectedBuilding.replace(/\s+/g, '-')}-${new Date().toISOString().slice(0, 10)}.${ext}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      setGenerating(null);
      setGenerated(report.id);
      setTimeout(() => setGenerated(null), 3000);
    }, 1500);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      {/* Header */}
      <PageHeader
        title="Compliance Reports"
        description="Generate, view, and export detailed safety reports for your portfolio."
      />

      {/* Filters */}
      <div className="card" style={{ padding: '20px 24px' }}>
        <div style={{ display: 'flex', gap: 16, alignItems: 'center', flexWrap: 'wrap' }}>
          <div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 6, fontWeight: 500 }}>Scope</div>
            <select className="select" value={selectedBuilding} onChange={e => setSelectedBuilding(e.target.value)} style={{ width: 200 }}>
              <option value="All Buildings">All Buildings</option>
              {buildings.map(b => (
                <option key={b.id} value={b.name}>{b.name}</option>
              ))}
            </select>
          </div>
          <div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 6, fontWeight: 500 }}>Period</div>
            <select className="select" value={selectedPeriod} onChange={e => setSelectedPeriod(e.target.value)} style={{ width: 200 }}>
              <option value="Q2 2026 (Apr-Jun)">Q2 2026 (Apr-Jun)</option>
              <option value="Q1 2026 (Jan-Mar)">Q1 2026 (Jan-Mar)</option>
              <option value="Full Year 2025">Full Year 2025</option>
              <option value="Last 90 Days">Last 90 Days</option>
              <option value="Last 30 Days">Last 30 Days</option>
              <option value="Custom Range">Custom Range</option>
            </select>
          </div>
          <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 8, paddingTop: 20 }}>
            <div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>
              Scope: <strong>{selectedBuilding}</strong> · {selectedPeriod}
            </div>
          </div>
        </div>
      </div>

      {/* Report Cards */}
      <div className="dashboard-grid-half" style={{ gap: 20 }}>
        {reports.map(report => {
          const Icon = report.icon;
          const isGenerating = generating === report.id;
          const isGenerated = generated === report.id;

          return (
            <div key={report.id} className="report-card">
              <div style={{ display: 'flex', alignItems: 'flex-start', gap: 16 }}>
                <div className="report-icon" style={{ background: report.bg, flexShrink: 0 }}>
                  <Icon size={24} color={report.color} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 15, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 6 }}>{report.title}</div>
                  <div style={{ fontSize: 12.5, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{report.description}</div>
                </div>
              </div>

              <div style={{ display: 'flex', gap: 8, alignItems: 'center', paddingTop: 4 }}>
                <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>~{report.pages}</span>
                <span style={{ fontSize: 11, color: 'var(--border-color)' }}>·</span>
                <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>Last: {report.lastGenerated}</span>
              </div>

              <div style={{ borderTop: '1px solid var(--border-light)', paddingTop: 16, display: 'flex', gap: 10, alignItems: 'center' }}>
                {isGenerated ? (
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'var(--status-success)', fontSize: 13, fontWeight: 600 }}>
                    <CheckCircle size={16} />
                    Report generated! Downloading...
                  </div>
                ) : (
                  <>
                    {report.formats.map(fmt => (
                      <button
                        key={fmt}
                        className={fmt === 'PDF' ? 'btn btn-primary btn-sm' : 'btn btn-secondary btn-sm'}
                        onClick={() => handleGenerate(report, fmt)}
                        disabled={isGenerating}
                        style={{ display: 'flex', alignItems: 'center', gap: 6 }}
                      >
                        {isGenerating ? (
                          <>
                            <div style={{
                              width: 12, height: 12, border: '2px solid currentColor',
                              borderTopColor: 'transparent', borderRadius: '50%',
                              animation: 'spin 0.8s linear infinite'
                            }} />
                            Generating...
                          </>
                        ) : (
                          <><Download size={12} /> {fmt}</>
                        )}
                      </button>
                    ))}
                    <span style={{ fontSize: 11.5, color: 'var(--text-muted)', marginLeft: 'auto' }}>
                      PDF · Excel · Shareable link
                    </span>
                  </>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Recent Reports */}
      <div className="card">
        <div className="card-header">
          <div className="card-title">Recent Reports</div>
          <button className="btn btn-ghost btn-sm" onClick={() => alert('Showing all generated reports. In production, this would navigate to a report archive page.')}>View All</button>
        </div>
        <div className="table-container hidden-on-mobile" style={{ border: 'none', borderRadius: 0, marginTop: 12 }}>
          <table className="data-table">
            <thead>
              <tr>
                <th>Report Name</th>
                <th>Type</th>
                <th>Generated</th>
                <th>Size</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredRecentReports.map((report, i) => (
                <tr key={i}>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                      <div style={{
                        width: 32, height: 32, borderRadius: 8,
                        background: report.type === 'PDF' ? '#FEF2F2' : '#F0FDF4',
                        display: 'flex', alignItems: 'center', justifyContent: 'center'
                      }}>
                        <FileText size={14} color={report.type === 'PDF' ? '#DC2626' : '#16A34A'} />
                      </div>
                      <span style={{ fontSize: 13, fontWeight: 500 }}>{report.name}</span>
                    </div>
                  </td>
                  <td>
                    <span className={`badge badge-${report.type === 'PDF' ? 'danger' : 'success'}`} style={{ fontSize: 10 }}>
                      {report.type}
                    </span>
                  </td>
                  <td style={{ fontSize: 12, color: 'var(--text-secondary)' }}>{report.date}</td>
                  <td style={{ fontSize: 12, color: 'var(--text-secondary)' }}>{report.size}</td>
                  <td>
                    <div style={{ display: 'flex', gap: 8 }}>
                      <button className="btn btn-ghost btn-sm btn-icon" title="Download" onClick={() => handleGenerate({ id: `recent-${i}`, title: report.name }, report.type)}>
                        <Download size={13} />
                      </button>
                      <button className="btn btn-ghost btn-sm" style={{ fontSize: 11 }} onClick={() => {
                        const shareUrl = `${window.location.origin}/reports/${report.name.replace(/\s+/g, '-').toLowerCase()}`;
                        navigator.clipboard?.writeText(shareUrl).then(() => {
                          alert('Share link copied to clipboard!');
                        }).catch(() => {
                          alert(`Share link: ${shareUrl}`);
                        });
                      }}>Share</button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Mobile Cards for Recent Reports */}
        <div className="show-on-mobile" style={{ marginTop: 16 }}>
          {filteredRecentReports.map((report, i) => (
            <div key={i} className="mobile-card">
              <div className="mobile-card-header">
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <div style={{
                    width: 36, height: 36, borderRadius: 'var(--radius-md)',
                    background: report.type === 'PDF' ? '#FEF2F2' : '#F0FDF4',
                    display: 'flex', alignItems: 'center', justifyContent: 'center'
                  }}>
                    <FileText size={16} color={report.type === 'PDF' ? '#DC2626' : '#16A34A'} />
                  </div>
                  <div>
                    <div className="mobile-card-title">{report.name}</div>
                    <div className="mobile-card-subtitle">{report.date} · {report.size}</div>
                  </div>
                </div>
              </div>
              <div className="mobile-card-actions">
                <button className="btn btn-primary btn-sm" style={{ flex: 1, justifyContent: 'center' }} onClick={() => handleGenerate({ id: `recent-${i}`, title: report.name }, report.type)}>
                  <Download size={13} style={{ marginRight: 4 }}/> Download
                </button>
                <button className="btn btn-secondary btn-sm" style={{ flex: 1, justifyContent: 'center' }} onClick={() => {
                  const shareUrl = `${window.location.origin}/reports/${report.name.replace(/\s+/g, '-').toLowerCase()}`;
                  navigator.clipboard?.writeText(shareUrl).then(() => {
                    alert('Share link copied to clipboard!');
                  }).catch(() => {
                    alert(`Share link: ${shareUrl}`);
                  });
                }}>Share</button>
              </div>
            </div>
          ))}
        </div>
      </div>

      <style>{`
      `}</style>
    </div>
  );
}
